from datetime import datetime

# Copa do Mundo 2026 - TODOS os Jogos (Fase de Grupos + Mata-Mata)
# match_date armazena o horário de Brasília (UTC-3)

matches_data = [
    # ===== 1ª RODADA =====
    # Quinta-feira, 11 de junho de 2026
    {"match_number": 1, "group": "A", "team_a": "México", "team_b": "África do Sul", "team_a_code": "MEX", "team_b_code": "RSA", "match_date": datetime(2026, 6, 11, 16, 0), "local_time": "13:00", "brasilia_time": "16:00", "city": "Cidade do México", "stadium": "Estádio Azteca", "round_number": 1, "stage": "group_stage"},
    {"match_number": 2, "group": "A", "team_a": "República da Coreia", "team_b": "República Tcheca", "team_a_code": "KOR", "team_b_code": "CZE", "match_date": datetime(2026, 6, 11, 23, 0), "local_time": "20:00", "brasilia_time": "23:00", "city": "Guadalajara", "stadium": "Estádio Akron", "round_number": 1, "stage": "group_stage"},
    # Sexta-feira, 12 de junho de 2026
    {"match_number": 3, "group": "B", "team_a": "Canadá", "team_b": "Bósnia e Herzegovina", "team_a_code": "CAN", "team_b_code": "BIH", "match_date": datetime(2026, 6, 12, 16, 0), "local_time": "15:00", "brasilia_time": "16:00", "city": "Toronto", "stadium": "BMO Field", "round_number": 1, "stage": "group_stage"},
    {"match_number": 4, "group": "D", "team_a": "Estados Unidos", "team_b": "Paraguai", "team_a_code": "USA", "team_b_code": "PAR", "match_date": datetime(2026, 6, 12, 22, 0), "local_time": "18:00", "brasilia_time": "22:00", "city": "Los Angeles", "stadium": "SoFi Stadium", "round_number": 1, "stage": "group_stage"},
    # Sábado, 13 de junho de 2026
    {"match_number": 5, "group": "B", "team_a": "Catar", "team_b": "Suíça", "team_a_code": "QAT", "team_b_code": "SUI", "match_date": datetime(2026, 6, 13, 16, 0), "local_time": "12:00", "brasilia_time": "16:00", "city": "Santa Clara", "stadium": "Levi's Stadium", "round_number": 1, "stage": "group_stage"},
    {"match_number": 6, "group": "C", "team_a": "Brasil", "team_b": "Marrocos", "team_a_code": "BRA", "team_b_code": "MAR", "match_date": datetime(2026, 6, 13, 19, 0), "local_time": "18:00", "brasilia_time": "19:00", "city": "Nova York/Nova Jersey", "stadium": "MetLife Stadium", "round_number": 1, "stage": "group_stage"},
    {"match_number": 7, "group": "C", "team_a": "Haiti", "team_b": "Escócia", "team_a_code": "HAI", "team_b_code": "SCO", "match_date": datetime(2026, 6, 13, 22, 0), "local_time": "21:00", "brasilia_time": "22:00", "city": "Boston", "stadium": "Gillette Stadium", "round_number": 1, "stage": "group_stage"},
    {"match_number": 8, "group": "D", "team_a": "Austrália", "team_b": "Turquia", "team_a_code": "AUS", "team_b_code": "TUR", "match_date": datetime(2026, 6, 14, 1, 0), "local_time": "21:00", "brasilia_time": "01:00", "city": "Vancouver", "stadium": "BC Place", "round_number": 1, "stage": "group_stage"},
    # Domingo, 14 de junho de 2026
    {"match_number": 9, "group": "E", "team_a": "Alemanha", "team_b": "Curaçao", "team_a_code": "GER", "team_b_code": "CUW", "match_date": datetime(2026, 6, 14, 14, 0), "local_time": "12:00", "brasilia_time": "14:00", "city": "Houston", "stadium": "NRG Stadium", "round_number": 1, "stage": "group_stage"},
    {"match_number": 10, "group": "E", "team_a": "Costa do Marfim", "team_b": "Equador", "team_a_code": "CIV", "team_b_code": "ECU", "match_date": datetime(2026, 6, 14, 20, 0), "local_time": "19:00", "brasilia_time": "20:00", "city": "Filadélfia", "stadium": "Lincoln Financial Field", "round_number": 1, "stage": "group_stage"},
    {"match_number": 11, "group": "F", "team_a": "Holanda", "team_b": "Japão", "team_a_code": "NED", "team_b_code": "JPN", "match_date": datetime(2026, 6, 14, 17, 0), "local_time": "15:00", "brasilia_time": "17:00", "city": "Dallas", "stadium": "AT&T Stadium", "round_number": 1, "stage": "group_stage"},
    {"match_number": 12, "group": "F", "team_a": "Suécia", "team_b": "Tunísia", "team_a_code": "SWE", "team_b_code": "TUN", "match_date": datetime(2026, 6, 14, 23, 0), "local_time": "20:00", "brasilia_time": "23:00", "city": "Monterrey", "stadium": "Estádio BBVA", "round_number": 1, "stage": "group_stage"},
    # Segunda-feira, 15 de junho de 2026
    {"match_number": 13, "group": "H", "team_a": "Espanha", "team_b": "Cabo Verde", "team_a_code": "ESP", "team_b_code": "CPV", "match_date": datetime(2026, 6, 15, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Atlanta", "stadium": "Mercedes-Benz Stadium", "round_number": 1, "stage": "group_stage"},
    {"match_number": 14, "group": "H", "team_a": "Arábia Saudita", "team_b": "Uruguai", "team_a_code": "KSA", "team_b_code": "URU", "match_date": datetime(2026, 6, 15, 19, 0), "local_time": "18:00", "brasilia_time": "19:00", "city": "Miami", "stadium": "Hard Rock Stadium", "round_number": 1, "stage": "group_stage"},
    {"match_number": 15, "group": "G", "team_a": "Bélgica", "team_b": "Egito", "team_a_code": "BEL", "team_b_code": "EGY", "match_date": datetime(2026, 6, 15, 16, 0), "local_time": "12:00", "brasilia_time": "16:00", "city": "Seattle", "stadium": "Lumen Field", "round_number": 1, "stage": "group_stage"},
    {"match_number": 16, "group": "G", "team_a": "Irã", "team_b": "Nova Zelândia", "team_a_code": "IRN", "team_b_code": "NZL", "match_date": datetime(2026, 6, 15, 22, 0), "local_time": "18:00", "brasilia_time": "22:00", "city": "Los Angeles", "stadium": "SoFi Stadium", "round_number": 1, "stage": "group_stage"},
    # Terça-feira, 16 de junho de 2026
    {"match_number": 17, "group": "J", "team_a": "Áustria", "team_b": "Jordânia", "team_a_code": "AUT", "team_b_code": "JOR", "match_date": datetime(2026, 6, 17, 1, 0), "local_time": "21:00", "brasilia_time": "01:00", "city": "Santa Clara", "stadium": "Levi's Stadium", "round_number": 1, "stage": "group_stage"},
    {"match_number": 18, "group": "I", "team_a": "França", "team_b": "Senegal", "team_a_code": "FRA", "team_b_code": "SEN", "match_date": datetime(2026, 6, 16, 16, 0), "local_time": "15:00", "brasilia_time": "16:00", "city": "Nova York/Nova Jersey", "stadium": "MetLife Stadium", "round_number": 1, "stage": "group_stage"},
    {"match_number": 19, "group": "I", "team_a": "Iraque", "team_b": "Noruega", "team_a_code": "IRQ", "team_b_code": "NOR", "match_date": datetime(2026, 6, 16, 19, 0), "local_time": "18:00", "brasilia_time": "19:00", "city": "Boston", "stadium": "Gillette Stadium", "round_number": 1, "stage": "group_stage"},
    {"match_number": 20, "group": "J", "team_a": "Argentina", "team_b": "Argélia", "team_a_code": "ARG", "team_b_code": "ALG", "match_date": datetime(2026, 6, 16, 21, 0), "local_time": "20:00", "brasilia_time": "22:00", "city": "Kansas City", "stadium": "Arrowhead Stadium", "round_number": 1, "stage": "group_stage"},
    # Quarta-feira, 17 de junho de 2026
    {"match_number": 21, "group": "K", "team_a": "Portugal", "team_b": "República Democrática do Congo", "team_a_code": "POR", "team_b_code": "COD", "match_date": datetime(2026, 6, 17, 14, 0), "local_time": "12:00", "brasilia_time": "14:00", "city": "Houston", "stadium": "NRG Stadium", "round_number": 1, "stage": "group_stage"},
    {"match_number": 22, "group": "L", "team_a": "Inglaterra", "team_b": "Croácia", "team_a_code": "ENG", "team_b_code": "CRO", "match_date": datetime(2026, 6, 17, 17, 0), "local_time": "15:00", "brasilia_time": "17:00", "city": "Dallas", "stadium": "AT&T Stadium", "round_number": 1, "stage": "group_stage"},
    {"match_number": 23, "group": "L", "team_a": "Gana", "team_b": "Panamá", "team_a_code": "GHA", "team_b_code": "PAN", "match_date": datetime(2026, 6, 17, 20, 0), "local_time": "19:00", "brasilia_time": "20:00", "city": "Toronto", "stadium": "BMO Field", "round_number": 1, "stage": "group_stage"},
    {"match_number": 24, "group": "K", "team_a": "Uzbequistão", "team_b": "Colômbia", "team_a_code": "UZB", "team_b_code": "COL", "match_date": datetime(2026, 6, 17, 21, 0), "local_time": "20:00", "brasilia_time": "21:00", "city": "Cidade do México", "stadium": "Estádio Azteca", "round_number": 1, "stage": "group_stage"},

    # ===== 2ª RODADA =====
    # Quinta-feira, 18 de junho de 2026
    {"match_number": 25, "group": "A", "team_a": "República Tcheca", "team_b": "África do Sul", "team_a_code": "CZE", "team_b_code": "RSA", "match_date": datetime(2026, 6, 18, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Atlanta", "stadium": "Mercedes-Benz Stadium", "round_number": 2, "stage": "group_stage"},
    {"match_number": 26, "group": "B", "team_a": "Suíça", "team_b": "Bósnia e Herzegovina", "team_a_code": "SUI", "team_b_code": "BIH", "match_date": datetime(2026, 6, 18, 16, 0), "local_time": "12:00", "brasilia_time": "16:00", "city": "Los Angeles", "stadium": "SoFi Stadium", "round_number": 2, "stage": "group_stage"},
    {"match_number": 27, "group": "B", "team_a": "Canadá", "team_b": "Catar", "team_a_code": "CAN", "team_b_code": "QAT", "match_date": datetime(2026, 6, 18, 19, 0), "local_time": "15:00", "brasilia_time": "19:00", "city": "Vancouver", "stadium": "BC Place", "round_number": 2, "stage": "group_stage"},
    {"match_number": 28, "group": "A", "team_a": "México", "team_b": "República da Coreia", "team_a_code": "MEX", "team_b_code": "KOR", "match_date": datetime(2026, 6, 18, 22, 0), "local_time": "19:00", "brasilia_time": "22:00", "city": "Guadalajara", "stadium": "Estádio Akron", "round_number": 2, "stage": "group_stage"},
    # Sexta-feira, 19 de junho de 2026
    {"match_number": 29, "group": "D", "team_a": "Turquia", "team_b": "Paraguai", "team_a_code": "TUR", "team_b_code": "PAR", "match_date": datetime(2026, 6, 19, 0, 0), "local_time": "20:00", "brasilia_time": "00:00", "city": "Santa Clara", "stadium": "Levi's Stadium", "round_number": 2, "stage": "group_stage"},
    {"match_number": 30, "group": "D", "team_a": "Estados Unidos", "team_b": "Austrália", "team_a_code": "USA", "team_b_code": "AUS", "match_date": datetime(2026, 6, 19, 16, 0), "local_time": "12:00", "brasilia_time": "16:00", "city": "Seattle", "stadium": "Lumen Field", "round_number": 2, "stage": "group_stage"},
    {"match_number": 31, "group": "C", "team_a": "Escócia", "team_b": "Marrocos", "team_a_code": "SCO", "team_b_code": "MAR", "match_date": datetime(2026, 6, 19, 19, 0), "local_time": "18:00", "brasilia_time": "19:00", "city": "Boston", "stadium": "Gillette Stadium", "round_number": 2, "stage": "group_stage"},
    {"match_number": 32, "group": "C", "team_a": "Brasil", "team_b": "Haiti", "team_a_code": "BRA", "team_b_code": "HAI", "match_date": datetime(2026, 6, 19, 20, 30), "local_time": "20:30", "brasilia_time": "21:30", "city": "Filadélfia", "stadium": "Lincoln Financial Field", "round_number": 2, "stage": "group_stage"},
    # Sábado, 20 de junho de 2026
    {"match_number": 33, "group": "F", "team_a": "Tunísia", "team_b": "Japão", "team_a_code": "TUN", "team_b_code": "JPN", "match_date": datetime(2026, 6, 20, 23, 0), "local_time": "20:00", "brasilia_time": "23:00", "city": "Monterrey", "stadium": "Estádio BBVA", "round_number": 2, "stage": "group_stage"},
    {"match_number": 34, "group": "F", "team_a": "Holanda", "team_b": "Suécia", "team_a_code": "NED", "team_b_code": "SWE", "match_date": datetime(2026, 6, 20, 14, 0), "local_time": "12:00", "brasilia_time": "14:00", "city": "Houston", "stadium": "NRG Stadium", "round_number": 2, "stage": "group_stage"},
    {"match_number": 35, "group": "E", "team_a": "Alemanha", "team_b": "Costa do Marfim", "team_a_code": "GER", "team_b_code": "CIV", "match_date": datetime(2026, 6, 20, 17, 0), "local_time": "16:00", "brasilia_time": "17:00", "city": "Toronto", "stadium": "BMO Field", "round_number": 2, "stage": "group_stage"},
    {"match_number": 36, "group": "E", "team_a": "Equador", "team_b": "Curaçao", "team_a_code": "ECU", "team_b_code": "CUW", "match_date": datetime(2026, 6, 20, 20, 0), "local_time": "19:00", "brasilia_time": "21:00", "city": "Kansas City", "stadium": "Arrowhead Stadium", "round_number": 2, "stage": "group_stage"},
    # Domingo, 21 de junho de 2026
    {"match_number": 37, "group": "H", "team_a": "Espanha", "team_b": "Arábia Saudita", "team_a_code": "ESP", "team_b_code": "KSA", "match_date": datetime(2026, 6, 21, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Atlanta", "stadium": "Mercedes-Benz Stadium", "round_number": 2, "stage": "group_stage"},
    {"match_number": 38, "group": "G", "team_a": "Bélgica", "team_b": "Irã", "team_a_code": "BEL", "team_b_code": "IRN", "match_date": datetime(2026, 6, 21, 16, 0), "local_time": "12:00", "brasilia_time": "16:00", "city": "Los Angeles", "stadium": "SoFi Stadium", "round_number": 2, "stage": "group_stage"},
    {"match_number": 39, "group": "H", "team_a": "Uruguai", "team_b": "Cabo Verde", "team_a_code": "URU", "team_b_code": "CPV", "match_date": datetime(2026, 6, 21, 19, 0), "local_time": "18:00", "brasilia_time": "19:00", "city": "Miami", "stadium": "Hard Rock Stadium", "round_number": 2, "stage": "group_stage"},
    {"match_number": 40, "group": "G", "team_a": "Nova Zelândia", "team_b": "Egito", "team_a_code": "NZL", "team_b_code": "EGY", "match_date": datetime(2026, 6, 21, 20, 0), "local_time": "18:00", "brasilia_time": "22:00", "city": "Vancouver", "stadium": "BC Place", "round_number": 2, "stage": "group_stage"},
    # Segunda-feira, 22 de junho de 2026
    {"match_number": 41, "group": "J", "team_a": "Argentina", "team_b": "Áustria", "team_a_code": "ARG", "team_b_code": "AUT", "match_date": datetime(2026, 6, 22, 14, 0), "local_time": "12:00", "brasilia_time": "14:00", "city": "Dallas", "stadium": "AT&T Stadium", "round_number": 2, "stage": "group_stage"},
    {"match_number": 42, "group": "I", "team_a": "França", "team_b": "Iraque", "team_a_code": "FRA", "team_b_code": "IRQ", "match_date": datetime(2026, 6, 22, 18, 0), "local_time": "17:00", "brasilia_time": "18:00", "city": "Filadélfia", "stadium": "Lincoln Financial Field", "round_number": 2, "stage": "group_stage"},
    {"match_number": 43, "group": "I", "team_a": "Noruega", "team_b": "Senegal", "team_a_code": "NOR", "team_b_code": "SEN", "match_date": datetime(2026, 6, 22, 21, 0), "local_time": "20:00", "brasilia_time": "21:00", "city": "Nova York/Nova Jersey", "stadium": "MetLife Stadium", "round_number": 2, "stage": "group_stage"},
    {"match_number": 44, "group": "J", "team_a": "Jordânia", "team_b": "Argélia", "team_a_code": "JOR", "team_b_code": "ALG", "match_date": datetime(2026, 6, 23, 0, 0), "local_time": "20:00", "brasilia_time": "00:00", "city": "Santa Clara", "stadium": "Levi's Stadium", "round_number": 2, "stage": "group_stage"},
    # Terça-feira, 23 de junho de 2026
    {"match_number": 45, "group": "K", "team_a": "Portugal", "team_b": "Uzbequistão", "team_a_code": "POR", "team_b_code": "UZB", "match_date": datetime(2026, 6, 23, 14, 0), "local_time": "12:00", "brasilia_time": "14:00", "city": "Houston", "stadium": "NRG Stadium", "round_number": 2, "stage": "group_stage"},
    {"match_number": 46, "group": "L", "team_a": "Inglaterra", "team_b": "Gana", "team_a_code": "ENG", "team_b_code": "GHA", "match_date": datetime(2026, 6, 23, 17, 0), "local_time": "16:00", "brasilia_time": "17:00", "city": "Boston", "stadium": "Gillette Stadium", "round_number": 2, "stage": "group_stage"},
    {"match_number": 47, "group": "L", "team_a": "Panamá", "team_b": "Croácia", "team_a_code": "PAN", "team_b_code": "CRO", "match_date": datetime(2026, 6, 23, 20, 0), "local_time": "19:00", "brasilia_time": "20:00", "city": "Toronto", "stadium": "BMO Field", "round_number": 2, "stage": "group_stage"},
    {"match_number": 48, "group": "K", "team_a": "Colômbia", "team_b": "República Democrática do Congo", "team_a_code": "COL", "team_b_code": "COD", "match_date": datetime(2026, 6, 23, 21, 0), "local_time": "20:00", "brasilia_time": "21:00", "city": "Guadalajara", "stadium": "Estádio Akron", "round_number": 2, "stage": "group_stage"},

    # ===== 3ª RODADA =====
    # Quarta-feira, 24 de junho de 2026
    {"match_number": 49, "group": "B", "team_a": "Suíça", "team_b": "Canadá", "team_a_code": "SUI", "team_b_code": "CAN", "match_date": datetime(2026, 6, 24, 16, 0), "local_time": "12:00", "brasilia_time": "16:00", "city": "Vancouver", "stadium": "BC Place", "round_number": 3, "stage": "group_stage"},
    {"match_number": 50, "group": "B", "team_a": "Bósnia e Herzegovina", "team_b": "Catar", "team_a_code": "BIH", "team_b_code": "QAT", "match_date": datetime(2026, 6, 24, 16, 0), "local_time": "12:00", "brasilia_time": "16:00", "city": "Seattle", "stadium": "Lumen Field", "round_number": 3, "stage": "group_stage"},
    {"match_number": 51, "group": "C", "team_a": "Escócia", "team_b": "Brasil", "team_a_code": "SCO", "team_b_code": "BRA", "match_date": datetime(2026, 6, 24, 19, 0), "local_time": "18:00", "brasilia_time": "19:00", "city": "Miami", "stadium": "Hard Rock Stadium", "round_number": 3, "stage": "group_stage"},
    {"match_number": 52, "group": "C", "team_a": "Marrocos", "team_b": "Haiti", "team_a_code": "MAR", "team_b_code": "HAI", "match_date": datetime(2026, 6, 24, 19, 0), "local_time": "18:00", "brasilia_time": "19:00", "city": "Atlanta", "stadium": "Mercedes-Benz Stadium", "round_number": 3, "stage": "group_stage"},
    {"match_number": 53, "group": "A", "team_a": "República Tcheca", "team_b": "México", "team_a_code": "CZE", "team_b_code": "MEX", "match_date": datetime(2026, 6, 24, 22, 0), "local_time": "19:00", "brasilia_time": "22:00", "city": "Cidade do México", "stadium": "Estádio Azteca", "round_number": 3, "stage": "group_stage"},
    {"match_number": 54, "group": "A", "team_a": "África do Sul", "team_b": "República da Coreia", "team_a_code": "RSA", "team_b_code": "KOR", "match_date": datetime(2026, 6, 24, 22, 0), "local_time": "19:00", "brasilia_time": "22:00", "city": "Monterrey", "stadium": "Estádio BBVA", "round_number": 3, "stage": "group_stage"},
    # Quinta-feira, 25 de junho de 2026
    {"match_number": 55, "group": "E", "team_a": "Equador", "team_b": "Alemanha", "team_a_code": "ECU", "team_b_code": "GER", "match_date": datetime(2026, 6, 25, 17, 0), "local_time": "16:00", "brasilia_time": "17:00", "city": "Nova York/Nova Jersey", "stadium": "MetLife Stadium", "round_number": 3, "stage": "group_stage"},
    {"match_number": 56, "group": "E", "team_a": "Curaçao", "team_b": "Costa do Marfim", "team_a_code": "CUW", "team_b_code": "CIV", "match_date": datetime(2026, 6, 25, 17, 0), "local_time": "16:00", "brasilia_time": "17:00", "city": "Filadélfia", "stadium": "Lincoln Financial Field", "round_number": 3, "stage": "group_stage"},
    {"match_number": 57, "group": "F", "team_a": "Japão", "team_b": "Suécia", "team_a_code": "JPN", "team_b_code": "SWE", "match_date": datetime(2026, 6, 25, 20, 0), "local_time": "18:00", "brasilia_time": "20:00", "city": "Dallas", "stadium": "AT&T Stadium", "round_number": 3, "stage": "group_stage"},
    {"match_number": 58, "group": "F", "team_a": "Tunísia", "team_b": "Holanda", "team_a_code": "TUN", "team_b_code": "NED", "match_date": datetime(2026, 6, 25, 20, 0), "local_time": "18:00", "brasilia_time": "20:00", "city": "Kansas City", "stadium": "Arrowhead Stadium", "round_number": 3, "stage": "group_stage"},
    {"match_number": 59, "group": "D", "team_a": "Turquia", "team_b": "Estados Unidos", "team_a_code": "TUR", "team_b_code": "USA", "match_date": datetime(2026, 6, 26, 0, 0), "local_time": "19:00", "brasilia_time": "23:00", "city": "Los Angeles", "stadium": "SoFi Stadium", "round_number": 3, "stage": "group_stage"},
    {"match_number": 60, "group": "D", "team_a": "Paraguai", "team_b": "Austrália", "team_a_code": "PAR", "team_b_code": "AUS", "match_date": datetime(2026, 6, 26, 0, 0), "local_time": "19:00", "brasilia_time": "23:00", "city": "Santa Clara", "stadium": "Levi's Stadium", "round_number": 3, "stage": "group_stage"},
    # Sexta-feira, 26 de junho de 2026
    {"match_number": 61, "group": "I", "team_a": "Noruega", "team_b": "França", "team_a_code": "NOR", "team_b_code": "FRA", "match_date": datetime(2026, 6, 26, 16, 0), "local_time": "15:00", "brasilia_time": "16:00", "city": "Boston", "stadium": "Gillette Stadium", "round_number": 3, "stage": "group_stage"},
    {"match_number": 62, "group": "I", "team_a": "Senegal", "team_b": "Iraque", "team_a_code": "SEN", "team_b_code": "IRQ", "match_date": datetime(2026, 6, 26, 16, 0), "local_time": "15:00", "brasilia_time": "16:00", "city": "Toronto", "stadium": "BMO Field", "round_number": 3, "stage": "group_stage"},
    {"match_number": 63, "group": "H", "team_a": "Cabo Verde", "team_b": "Arábia Saudita", "team_a_code": "CPV", "team_b_code": "KSA", "match_date": datetime(2026, 6, 26, 21, 0), "local_time": "19:00", "brasilia_time": "21:00", "city": "Houston", "stadium": "NRG Stadium", "round_number": 3, "stage": "group_stage"},
    {"match_number": 64, "group": "H", "team_a": "Uruguai", "team_b": "Espanha", "team_a_code": "URU", "team_b_code": "ESP", "match_date": datetime(2026, 6, 26, 21, 0), "local_time": "18:00", "brasilia_time": "21:00", "city": "Guadalajara", "stadium": "Estádio Akron", "round_number": 3, "stage": "group_stage"},
    {"match_number": 65, "group": "G", "team_a": "Egito", "team_b": "Irã", "team_a_code": "EGY", "team_b_code": "IRN", "match_date": datetime(2026, 6, 27, 0, 0), "local_time": "20:00", "brasilia_time": "00:00", "city": "Seattle", "stadium": "Lumen Field", "round_number": 3, "stage": "group_stage"},
    {"match_number": 66, "group": "G", "team_a": "Nova Zelândia", "team_b": "Bélgica", "team_a_code": "NZL", "team_b_code": "BEL", "match_date": datetime(2026, 6, 27, 0, 0), "local_time": "20:00", "brasilia_time": "00:00", "city": "Vancouver", "stadium": "BC Place", "round_number": 3, "stage": "group_stage"},
    # Sábado, 27 de junho de 2026
    {"match_number": 67, "group": "L", "team_a": "Panamá", "team_b": "Inglaterra", "team_a_code": "PAN", "team_b_code": "ENG", "match_date": datetime(2026, 6, 27, 18, 0), "local_time": "17:00", "brasilia_time": "18:00", "city": "Nova York/Nova Jersey", "stadium": "MetLife Stadium", "round_number": 3, "stage": "group_stage"},
    {"match_number": 68, "group": "L", "team_a": "Croácia", "team_b": "Gana", "team_a_code": "CRO", "team_b_code": "GHA", "match_date": datetime(2026, 6, 27, 18, 0), "local_time": "17:00", "brasilia_time": "18:00", "city": "Filadélfia", "stadium": "Lincoln Financial Field", "round_number": 3, "stage": "group_stage"},
    {"match_number": 69, "group": "K", "team_a": "Colômbia", "team_b": "Portugal", "team_a_code": "COL", "team_b_code": "POR", "match_date": datetime(2026, 6, 27, 21, 30), "local_time": "19:30", "brasilia_time": "20:30", "city": "Miami", "stadium": "Hard Rock Stadium", "round_number": 3, "stage": "group_stage"},
    {"match_number": 70, "group": "K", "team_a": "República Democrática do Congo", "team_b": "Uzbequistão", "team_a_code": "COD", "team_b_code": "UZB", "match_date": datetime(2026, 6, 27, 21, 30), "local_time": "19:30", "brasilia_time": "20:30", "city": "Atlanta", "stadium": "Mercedes-Benz Stadium", "round_number": 3, "stage": "group_stage"},
    {"match_number": 71, "group": "J", "team_a": "Argélia", "team_b": "Áustria", "team_a_code": "ALG", "team_b_code": "AUT", "match_date": datetime(2026, 6, 27, 23, 0), "local_time": "21:00", "brasilia_time": "23:00", "city": "Kansas City", "stadium": "Arrowhead Stadium", "round_number": 3, "stage": "group_stage"},
    {"match_number": 72, "group": "J", "team_a": "Jordânia", "team_b": "Argentina", "team_a_code": "JOR", "team_b_code": "ARG", "match_date": datetime(2026, 6, 27, 23, 0), "local_time": "21:00", "brasilia_time": "23:00", "city": "Dallas", "stadium": "AT&T Stadium", "round_number": 3, "stage": "group_stage"},

    # ===== FASE DE 32 (MATA-MATA) =====
    # Domingo, 28 de junho de 2026
    {"match_number": 73, "group": None, "team_a": "2º Grupo A", "team_b": "2º Grupo B", "team_a_code": "2A", "team_b_code": "2B", "match_date": datetime(2026, 6, 28, 16, 0), "local_time": "15:00", "brasilia_time": "16:00", "city": "Los Angeles", "stadium": "SoFi Stadium", "round_number": 4, "stage": "round_of_32"},
    # Segunda-feira, 29 de junho de 2026
    {"match_number": 74, "group": None, "team_a": "1º Grupo E", "team_b": "3º A/B/C/D/F", "team_a_code": "1E", "team_b_code": "3AB", "match_date": datetime(2026, 6, 29, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Boston", "stadium": "Gillette Stadium", "round_number": 4, "stage": "round_of_32"},
    {"match_number": 75, "group": None, "team_a": "1º Grupo F", "team_b": "2º Grupo C", "team_a_code": "1F", "team_b_code": "2C", "match_date": datetime(2026, 6, 29, 16, 0), "local_time": "15:00", "brasilia_time": "16:00", "city": "Monterrey", "stadium": "Estádio BBVA", "round_number": 4, "stage": "round_of_32"},
    {"match_number": 76, "group": None, "team_a": "1º Grupo C", "team_b": "2º Grupo F", "team_a_code": "1C", "team_b_code": "2F", "match_date": datetime(2026, 6, 29, 19, 0), "local_time": "18:00", "brasilia_time": "19:00", "city": "Houston", "stadium": "NRG Stadium", "round_number": 4, "stage": "round_of_32"},
    # Terça-feira, 30 de junho de 2026
    {"match_number": 77, "group": None, "team_a": "1º Grupo I", "team_b": "3º C/D/F/G/H", "team_a_code": "1I", "team_b_code": "3CD", "match_date": datetime(2026, 6, 30, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Nova York/Nova Jersey", "stadium": "MetLife Stadium", "round_number": 4, "stage": "round_of_32"},
    {"match_number": 78, "group": None, "team_a": "2º Grupo E", "team_b": "2º Grupo I", "team_a_code": "2E", "team_b_code": "2I", "match_date": datetime(2026, 6, 30, 16, 0), "local_time": "15:00", "brasilia_time": "16:00", "city": "Dallas", "stadium": "AT&T Stadium", "round_number": 4, "stage": "round_of_32"},
    {"match_number": 79, "group": None, "team_a": "1º Grupo A", "team_b": "3º C/E/F/H/I", "team_a_code": "1A", "team_b_code": "3CE", "match_date": datetime(2026, 6, 30, 19, 0), "local_time": "18:00", "brasilia_time": "19:00", "city": "Cidade do México", "stadium": "Estádio Azteca", "round_number": 4, "stage": "round_of_32"},
    # Quarta-feira, 1º de julho de 2026
    {"match_number": 80, "group": None, "team_a": "1º Grupo L", "team_b": "3º E/H/I/J/K", "team_a_code": "1L", "team_b_code": "3EH", "match_date": datetime(2026, 7, 1, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Atlanta", "stadium": "Mercedes-Benz Stadium", "round_number": 4, "stage": "round_of_32"},
    {"match_number": 81, "group": None, "team_a": "1º Grupo D", "team_b": "3º B/E/F/I/J", "team_a_code": "1D", "team_b_code": "3BE", "match_date": datetime(2026, 7, 1, 16, 0), "local_time": "15:00", "brasilia_time": "16:00", "city": "Santa Clara", "stadium": "Levi's Stadium", "round_number": 4, "stage": "round_of_32"},
    {"match_number": 82, "group": None, "team_a": "1º Grupo G", "team_b": "3º A/E/H/I/J", "team_a_code": "1G", "team_b_code": "3AE", "match_date": datetime(2026, 7, 1, 19, 0), "local_time": "18:00", "brasilia_time": "19:00", "city": "Seattle", "stadium": "Lumen Field", "round_number": 4, "stage": "round_of_32"},
    # Quinta-feira, 2 de julho de 2026
    {"match_number": 83, "group": None, "team_a": "2º Grupo K", "team_b": "2º Grupo L", "team_a_code": "2K", "team_b_code": "2L", "match_date": datetime(2026, 7, 2, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Toronto", "stadium": "BMO Field", "round_number": 4, "stage": "round_of_32"},
    {"match_number": 84, "group": None, "team_a": "1º Grupo H", "team_b": "2º Grupo J", "team_a_code": "1H", "team_b_code": "2J", "match_date": datetime(2026, 7, 2, 16, 0), "local_time": "15:00", "brasilia_time": "16:00", "city": "Los Angeles", "stadium": "SoFi Stadium", "round_number": 4, "stage": "round_of_32"},
    {"match_number": 85, "group": None, "team_a": "1º Grupo B", "team_b": "3º E/F/G/I/J", "team_a_code": "1B", "team_b_code": "3EF", "match_date": datetime(2026, 7, 2, 19, 0), "local_time": "18:00", "brasilia_time": "19:00", "city": "Vancouver", "stadium": "BC Place", "round_number": 4, "stage": "round_of_32"},
    # Sexta-feira, 3 de julho de 2026
    {"match_number": 86, "group": None, "team_a": "1º Grupo J", "team_b": "2º Grupo H", "team_a_code": "1J", "team_b_code": "2H", "match_date": datetime(2026, 7, 3, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Miami", "stadium": "Hard Rock Stadium", "round_number": 4, "stage": "round_of_32"},
    {"match_number": 87, "group": None, "team_a": "1º Grupo K", "team_b": "3º D/E/I/J/L", "team_a_code": "1K", "team_b_code": "3DE", "match_date": datetime(2026, 7, 3, 16, 0), "local_time": "15:00", "brasilia_time": "16:00", "city": "Kansas City", "stadium": "Arrowhead Stadium", "round_number": 4, "stage": "round_of_32"},
    {"match_number": 88, "group": None, "team_a": "2º Grupo D", "team_b": "2º Grupo G", "team_a_code": "2D", "team_b_code": "2G", "match_date": datetime(2026, 7, 3, 19, 0), "local_time": "18:00", "brasilia_time": "19:00", "city": "Dallas", "stadium": "AT&T Stadium", "round_number": 4, "stage": "round_of_32"},

    # ===== OITAVAS DE FINAL =====
    # Sábado, 4 de julho de 2026
    {"match_number": 89, "group": None, "team_a": "Vencedor 74", "team_b": "Vencedor 77", "team_a_code": "W74", "team_b_code": "W77", "match_date": datetime(2026, 7, 4, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Filadélfia", "stadium": "Lincoln Financial Field", "round_number": 5, "stage": "round_of_16"},
    {"match_number": 90, "group": None, "team_a": "Vencedor 73", "team_b": "Vencedor 75", "team_a_code": "W73", "team_b_code": "W75", "match_date": datetime(2026, 7, 4, 16, 0), "local_time": "15:00", "brasilia_time": "16:00", "city": "Houston", "stadium": "NRG Stadium", "round_number": 5, "stage": "round_of_16"},
    # Domingo, 5 de julho de 2026
    {"match_number": 91, "group": None, "team_a": "Vencedor 76", "team_b": "Vencedor 78", "team_a_code": "W76", "team_b_code": "W78", "match_date": datetime(2026, 7, 5, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Nova York/Nova Jersey", "stadium": "MetLife Stadium", "round_number": 5, "stage": "round_of_16"},
    {"match_number": 92, "group": None, "team_a": "Vencedor 79", "team_b": "Vencedor 80", "team_a_code": "W79", "team_b_code": "W80", "match_date": datetime(2026, 7, 5, 16, 0), "local_time": "15:00", "brasilia_time": "16:00", "city": "Cidade do México", "stadium": "Estádio Azteca", "round_number": 5, "stage": "round_of_16"},
    # Segunda-feira, 6 de julho de 2026
    {"match_number": 93, "group": None, "team_a": "Vencedor 83", "team_b": "Vencedor 84", "team_a_code": "W83", "team_b_code": "W84", "match_date": datetime(2026, 7, 6, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Dallas", "stadium": "AT&T Stadium", "round_number": 5, "stage": "round_of_16"},
    {"match_number": 94, "group": None, "team_a": "Vencedor 81", "team_b": "Vencedor 82", "team_a_code": "W81", "team_b_code": "W82", "match_date": datetime(2026, 7, 6, 16, 0), "local_time": "15:00", "brasilia_time": "16:00", "city": "Seattle", "stadium": "Lumen Field", "round_number": 5, "stage": "round_of_16"},
    # Terça-feira, 7 de julho de 2026
    {"match_number": 95, "group": None, "team_a": "Vencedor 86", "team_b": "Vencedor 88", "team_a_code": "W86", "team_b_code": "W88", "match_date": datetime(2026, 7, 7, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Atlanta", "stadium": "Mercedes-Benz Stadium", "round_number": 5, "stage": "round_of_16"},
    {"match_number": 96, "group": None, "team_a": "Vencedor 85", "team_b": "Vencedor 87", "team_a_code": "W85", "team_b_code": "W87", "match_date": datetime(2026, 7, 7, 16, 0), "local_time": "15:00", "brasilia_time": "16:00", "city": "Vancouver", "stadium": "BC Place", "round_number": 5, "stage": "round_of_16"},

    # ===== QUARTAS DE FINAL =====
    # Quinta-feira, 9 de julho de 2026
    {"match_number": 97, "group": None, "team_a": "Vencedor 89", "team_b": "Vencedor 90", "team_a_code": "W89", "team_b_code": "W90", "match_date": datetime(2026, 7, 9, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Boston", "stadium": "Gillette Stadium", "round_number": 6, "stage": "quarter_final"},
    # Sexta-feira, 10 de julho de 2026
    {"match_number": 98, "group": None, "team_a": "Vencedor 93", "team_b": "Vencedor 94", "team_a_code": "W93", "team_b_code": "W94", "match_date": datetime(2026, 7, 10, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Los Angeles", "stadium": "SoFi Stadium", "round_number": 6, "stage": "quarter_final"},
    # Sábado, 12 de julho de 2026
    {"match_number": 99, "group": None, "team_a": "Vencedor 91", "team_b": "Vencedor 92", "team_a_code": "W91", "team_b_code": "W92", "match_date": datetime(2026, 7, 12, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Miami", "stadium": "Hard Rock Stadium", "round_number": 6, "stage": "quarter_final"},
    {"match_number": 100, "group": None, "team_a": "Vencedor 95", "team_b": "Vencedor 96", "team_a_code": "W95", "team_b_code": "W96", "match_date": datetime(2026, 7, 12, 16, 0), "local_time": "15:00", "brasilia_time": "16:00", "city": "Kansas City", "stadium": "Arrowhead Stadium", "round_number": 6, "stage": "quarter_final"},

    # ===== SEMIFINAIS =====
    # Terça-feira, 14 de julho de 2026
    {"match_number": 101, "group": None, "team_a": "Vencedor 97", "team_b": "Vencedor 98", "team_a_code": "W97", "team_b_code": "W98", "match_date": datetime(2026, 7, 14, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Dallas", "stadium": "AT&T Stadium", "round_number": 7, "stage": "semi_final"},
    # Quarta-feira, 15 de julho 2026
    {"match_number": 102, "group": None, "team_a": "Vencedor 99", "team_b": "Vencedor 100", "team_a_code": "W99", "team_b_code": "W100", "match_date": datetime(2026, 7, 15, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Atlanta", "stadium": "Mercedes-Benz Stadium", "round_number": 7, "stage": "semi_final"},

    # ===== DISPUTA 3º LUGAR =====
    # Sábado, 18 de julho de 2026
    {"match_number": 103, "group": None, "team_a": "Perdedor 101", "team_b": "Perdedor 102", "team_a_code": "L101", "team_b_code": "L102", "match_date": datetime(2026, 7, 18, 13, 0), "local_time": "12:00", "brasilia_time": "13:00", "city": "Miami", "stadium": "Hard Rock Stadium", "round_number": 8, "stage": "third_place"},

    # ===== FINAL =====
    # Domingo, 19 de julho de 2026
    {"match_number": 104, "group": None, "team_a": "Vencedor 101", "team_b": "Vencedor 102", "team_a_code": "W101", "team_b_code": "W102", "match_date": datetime(2026, 7, 19, 14, 0), "local_time": "13:00", "brasilia_time": "14:00", "city": "Nova York/Nova Jersey", "stadium": "MetLife Stadium", "round_number": 8, "stage": "final"},
]

# Total: 104 jogos da Copa do Mundo 2026
